WIP: Add compat for new AbstractCell type.
Ferrite-FEM/FerriteViz.jl pull request #78
Opened 2023-04-20 10:05 UTC by fredrikekre

2023-04-20 10:08 UTC, fredrikekre commented
I think the new interface will be a win in FerriteViz too, most dispatches seem to be based on the reference shape, which you can now to directly instead of figuring out the correct numbers in `Cell{refdim, nnodes, nfaces}`.

2023-04-20 15:20 UTC, termi-official commented
I introduced the abstract methods for now to have at least some kind of viz. Actually the high order stuff needs quite a different treatment but I could not find time yet.

2023-04-21 22:34 UTC, termi-official requested changes
LGTM otherwise. Fixing the first one should make the CI happy (fails because the first order refinement for interpolations is missing).

2023-04-21 22:34 UTC, termi-official commented on src/lor_tools.jl
> -for_nodes(::Union{Ferrite.Lagrange{2,Ferrite.RefTetrahedron,3},Ferrite.DiscontinuousLagrange{2,Ferrite.RefTetrahedron,3},Ferrite.Cell{2,10,3}}) = (
Note that this also includes the refinement for interpolations. Maybe we just want to remove the Cell from the type union for now. Same for ones below.

2023-04-21 22:34 UTC, termi-official commented on src/utils.jl
> +# ntriangles(cell::Ferrite.AbstractCell{3,N,1}) where N = 4 # Tets as a special case of a Quad, obviously :)
Can be removed now that embedded cells do not have the case distinction anymore.

```suggestion
```

2023-04-28 09:20 UTC, fredrikekre commented
I am donating this PR to someone who knows better :) The current changes are mostly mechanical without knowing much how these things are used.

2023-04-28 10:50 UTC, termi-official commented
Will take over then.

2023-10-14 00:54 UTC, termi-official commented
Handled in #103

2023-10-14 00:54 UTC, closed without merging